configure: introduce --static-zlib option
This allows to link with static zlib and its dependencies.

20210406  KONRAD Frederic <konrad@adacore.com>
    * meson.build: adapt to meson.

TN: T317-002
Change-Id: I2dd3e0adff3e01a76e2285cc107d60a3ebe41cac

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -333,6 +333,7 @@ ninja=""
 gio="$default_feature"
 static_glib="no"
 static_pixman="no"
+static_zlib="no"
 skip_meson=no
 
 # The following Meson options are handled manually (still they
@@ -1058,6 +1059,8 @@ for opt do
   ;;
   --static-pixman) static_pixman="yes"
   ;;
+  --static-zlib) static_zlib="yes"
+  ;;
   *)
       echo "ERROR: unknown option $opt"
       echo "Try '$0 --help' for more information"
@@ -1139,6 +1142,10 @@ if test "$static" = "yes"; then
     fi
     if test "$static_pixman" = "yes"; then
         echo "ERROR: --static and --static-pixman are not compatible"
+        exit 1
+    fi
+    if test "$static_zlib" = "yes"; then
+        echo "ERROR: --static and --static-zlib are not compatible"
         exit 1
     fi
 fi
@@ -2873,6 +2880,9 @@ if test "$static" = "yes" ; then
 fi
 if test "$static_pixman" = "yes" ; then
   echo "CONFIG_STATIC_PIXMAN=y" >> $config_host_mak
+fi
+if test "$static_zlib" = "yes" ; then
+  echo "CONFIG_STATIC_ZLIB=y" >> $config_host_mak
 fi
 echo "CONFIG_BDRV_RW_WHITELIST=$block_drv_rw_whitelist" >> $config_host_mak
 echo "CONFIG_BDRV_RO_WHITELIST=$block_drv_ro_whitelist" >> $config_host_mak
