configure: introduce --static-pixman option
This allows to link with static pixman and its dependencies.

20210406  KONRAD Frederic <konrad@adacore.com>
    * meson.build: adapt to meson.

TN: T317-002
Change-Id: I258e1e4ad0493d86cd668bd5042064ada6594d07

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -459,6 +459,7 @@ libdaxctl="$default_feature"
 meson=""
 ninja=""
 static_glib="no"
+static_pixman="no"
 skip_meson=no
 gettext="auto"
 fuse="auto"
@@ -1568,6 +1569,8 @@ for opt do
   ;;
   --disable-gio) gio=no
   ;;
+  --static-pixman) static_pixman="yes"
+  ;;
   *)
       echo "ERROR: unknown option $opt"
       echo "Try '$0 --help' for more information"
@@ -1613,6 +1616,10 @@ localedir="${localedir:-$datadir/locale}"
 if test "$static" = "yes"; then
     if test "$static_glib" = "yes"; then
         echo "ERROR: --static and --static-glib are not compatible"
+        exit 1
+    fi
+    if test "$static_pixman" = "yes"; then
+        echo "ERROR: --static and --static-pixman are not compatible"
         exit 1
     fi
 fi
@@ -5565,6 +5572,9 @@ if test "$haiku" = "yes" ; then
 fi
 if test "$static" = "yes" ; then
   echo "CONFIG_STATIC=y" >> $config_host_mak
+fi
+if test "$static_pixman" = "yes" ; then
+  echo "CONFIG_STATIC_PIXMAN=y" >> $config_host_mak
 fi
 if test "$profiler" = "yes" ; then
   echo "CONFIG_PROFILER=y" >> $config_host_mak
