configure: introduce --static-pixman option
This allows to link with static pixman and its dependencies.

TN: T317-002
Change-Id: I258e1e4ad0493d86cd668bd5042064ada6594d07

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -478,6 +478,7 @@ malloc_trim=""
 bridge_helper="yes"
 enable_roms="yes"
 static_glib="no"
+static_pixman="no"
 
 # parse CC options first
 for opt do
@@ -1431,6 +1432,8 @@ for opt do
   ;;
   --static-glib) static_glib="yes"
   ;;
+  --static-pixman) static_pixman="yes"
+  ;;
   *)
       echo "ERROR: unknown option $opt"
       echo "Try '$0 --help' for more information"
@@ -1444,6 +1447,10 @@ done
 if test "$static" = "yes"; then
     if test "$static_glib" = "yes"; then
         echo "ERROR: --static and --static-glib are not compatible"
+        exit 1
+    fi
+    if test "$static_pixman" = "yes"; then
+        echo "ERROR: --static and --static-pixman are not compatible"
         exit 1
     fi
 fi
@@ -3589,6 +3596,9 @@ if test "$want_tools" = "no" -a "$softmmu" = "no"; then
 elif $pkg_config --atleast-version=0.21.8 pixman-1 > /dev/null 2>&1; then
   pixman_cflags=$($pkg_config --cflags pixman-1)
   pixman_libs=$($pkg_config --libs pixman-1)
+  if test "$static_pixman" != "no"; then
+    pixman_libs="-Wl,-Bstatic $pixman_libs -Wl,-Bdynamic"
+  fi
 else
   error_exit "pixman >= 0.21.8 not present." \
       "Please install the pixman devel package."
