configure: introduce --static-pixman option
This allows to link with static pixman and its dependencies.

TN: T317-002
qemu#5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -469,6 +469,7 @@ multiprocess="auto"
 malloc_trim="auto"
 gio="$default_feature"
 static_glib="no"
+static_pixman="no"
 
 # parse CC options second
 for opt do
@@ -1579,6 +1580,8 @@ for opt do
   --disable-gio) gio=no
   --static-glib) static_glib="yes"
   ;;
+  --static-pixman) static_pixman="yes"
+  ;;
   *)
       echo "ERROR: unknown option $opt"
       echo "Try '$0 --help' for more information"
@@ -1624,6 +1627,10 @@ localedir="${localedir:-$datadir/locale}"
 if test "$static" = "yes"; then
     if test "$static_glib" = "yes"; then
         echo "ERROR: --static and --static-glib are not compatible"
+        exit 1
+    fi
+    if test "$static_pixman" = "yes"; then
+        echo "ERROR: --static and --static-pixman are not compatible"
         exit 1
     fi
 fi
@@ -3510,6 +3517,23 @@ if test "$modules" = yes; then
     if test "$shacmd" = ""; then
         error_exit "one of the checksum commands is required to enable modules: $shacmd_probe"
     fi
+fi
+
+##########################################
+# pixman support probe
+
+if test "$want_tools" = "no" && test "$softmmu" = "no"; then
+  pixman_cflags=
+  pixman_libs=
+elif $pkg_config --atleast-version=0.21.8 pixman-1 > /dev/null 2>&1; then
+  pixman_cflags=$($pkg_config --cflags pixman-1)
+  pixman_libs=$($pkg_config --libs pixman-1)
+  if test "$static_pixman" != "no"; then
+    pixman_libs="-Wl,-Bstatic $pixman_libs -Wl,-Bdynamic"
+  fi
+else
+  error_exit "pixman >= 0.21.8 not present." \
+      "Please install the pixman devel package."
 fi
 
 ##########################################
