configure: introduce --static-zlib option
This allows to link with static zlib and its dependencies.

TN: T317-002
Change-Id: I2dd3e0adff3e01a76e2285cc107d60a3ebe41cac

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -498,6 +498,7 @@ bridge_helper="yes"
 enable_roms="yes"
 static_glib="no"
 static_pixman="no"
+static_zlib="no"
 
 # parse CC options first
 for opt do
@@ -1593,6 +1594,8 @@ for opt do
   ;;
   --static-pixman) static_pixman="yes"
   ;;
+  --static-zlib) static_zlib="yes"
+  ;;
   *)
       echo "ERROR: unknown option $opt"
       echo "Try '$0 --help' for more information"
@@ -1610,6 +1613,10 @@ if test "$static" = "yes"; then
     fi
     if test "$static_pixman" = "yes"; then
         echo "ERROR: --static and --static-pixman are not compatible"
+        exit 1
+    fi
+    if test "$static_zlib" = "yes"; then
+        echo "ERROR: --static and --static-zlib are not compatible"
         exit 1
     fi
 fi
@@ -3930,8 +3937,14 @@ fi
 
 if test "$zlib" != "no" ; then
     if $pkg_config --exists zlib; then
-        zlib_cflags=$($pkg_config --cflags zlib)
-        zlib_libs=$($pkg_config --libs zlib)
+        if test "$static_zlib" != "no" ; then
+            zlib_cflags=$($pkg_config --static --cflags zlib)
+            zlib_libs=$($pkg_config --static --libs zlib)
+            zlib_libs="-Wl,-Bstatic $zlib_libs -Wl,-Bdynamic"
+        else
+            zlib_cflags=$($pkg_config --cflags zlib)
+            zlib_libs=$($pkg_config --libs zlib)
+        fi
         QEMU_CFLAGS="$zlib_cflags $QEMU_CFLAGS"
         LIBS="$zlib_libs $LIBS"
     else
@@ -3939,8 +3952,14 @@ if test "$zlib" != "no" ; then
 #include <zlib.h>
 int main(void) { zlibVersion(); return 0; }
 EOF
-        if compile_prog "" "-lz" ; then
-            LIBS="$LIBS -lz"
+        if test "$static_zlib" != "no" ; then
+            zlib_libs="-Wl,-Bstatic -lz -Wl,-Bdynamic"
+        else
+            zlib_libs="-lz"
+        fi
+
+        if compile_prog "" "$zlib_libs" ; then
+            LIBS="$LIBS $zlib_libs"
         else
             error_exit "zlib check failed" \
                 "Make sure to have the zlib libs and headers installed."
@@ -7333,6 +7352,10 @@ fi
 if test "$lzfse" = "yes" ; then
   echo "CONFIG_LZFSE=y" >> $config_host_mak
   echo "LZFSE_LIBS=-llzfse" >> $config_host_mak
+fi
+
+if test "$zlib" = "yes" ; then
+  echo "ZLIB_LIBS=$zlib_libs" >> $config_host_mak
 fi
 
 if test "$zstd" = "yes" ; then
