configure: introduce --static-glib option
This allows to link with static glib libraries and its dependencies.

TN: T317-002
Issue: eng/projects/scheme/scheme-deliverables#88

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -334,6 +334,7 @@ meson_args=""
 ninja=""
 gio="$default_feature"
 skip_meson=no
+static_glib="no"
 
 # The following Meson options are handled manually (still they
 # are included in the automatically generated help message)
@@ -1050,6 +1051,8 @@ for opt do
   ;;
   --disable-gio) gio=no
   ;;
+  --static-glib) static_glib="yes"
+  ;;
   # backwards compatibility options
   --enable-trace-backend=*) meson_option_parse "--enable-trace-backends=$optarg" "$optarg"
   ;;
@@ -1129,9 +1132,72 @@ local_statedir="${local_statedir:-$prefix/var}"
 firmwarepath="${firmwarepath:-$datadir/qemu-firmware}"
 localedir="${localedir:-$datadir/locale}"
 
+# Sanity check that we are not trying to enable --static-xxx and -static
+# at the same time.
+if test "$static" = "yes"; then
+    if test "$static_glib" = "yes"; then
+        echo "ERROR: --static and --static-glib are not compatible"
+        exit 1
+    fi
+fi
+
 if eval test -z "\${cross_cc_$cpu}"; then
     eval "cross_cc_${cpu}=\$cc"
     cross_cc_vars="$cross_cc_vars cross_cc_${cpu}"
+fi
+
+case "$cpu" in
+    ppc)
+           CPU_CFLAGS="-m32"
+           QEMU_LDFLAGS="-m32 $QEMU_LDFLAGS"
+           ;;
+    ppc64)
+           CPU_CFLAGS="-m64"
+           QEMU_LDFLAGS="-m64 $QEMU_LDFLAGS"
+           ;;
+    sparc)
+           CPU_CFLAGS="-m32 -mv8plus -mcpu=ultrasparc"
+           QEMU_LDFLAGS="-m32 -mv8plus $QEMU_LDFLAGS"
+           ;;
+    sparc64)
+           CPU_CFLAGS="-m64 -mcpu=ultrasparc"
+           QEMU_LDFLAGS="-m64 $QEMU_LDFLAGS"
+           ;;
+    s390)
+           CPU_CFLAGS="-m31"
+           QEMU_LDFLAGS="-m31 $QEMU_LDFLAGS"
+           ;;
+    s390x)
+           CPU_CFLAGS="-m64"
+           QEMU_LDFLAGS="-m64 $QEMU_LDFLAGS"
+           ;;
+    i386)
+           CPU_CFLAGS="-m32"
+           QEMU_LDFLAGS="-m32 $QEMU_LDFLAGS"
+           ;;
+    x86_64)
+           # ??? Only extremely old AMD cpus do not have cmpxchg16b.
+           # If we truly care, we should simply detect this case at
+           # runtime and generate the fallback to serial emulation.
+           CPU_CFLAGS="-m64 -mcx16"
+           QEMU_LDFLAGS="-m64 $QEMU_LDFLAGS"
+           ;;
+    x32)
+           CPU_CFLAGS="-mx32"
+           QEMU_LDFLAGS="-mx32 $QEMU_LDFLAGS"
+           ;;
+    # No special flags required for other host CPUs
+esac
+
+eval "cross_cc_${cpu}=\$host_cc"
+cross_cc_vars="$cross_cc_vars cross_cc_${cpu}"
+QEMU_CFLAGS="$CPU_CFLAGS $QEMU_CFLAGS"
+
+# For user-mode emulation the host arch has to be one we explicitly
+# support, even if we're using TCI.
+if [ "$ARCH" = "unknown" ]; then
+  bsd_user="no"
+  linux_user="no"
 fi
 
 default_target_list=""
@@ -2187,20 +2253,51 @@ elif test "$plugins" = "yes"; then
     glib_modules="$glib_modules gmodule-no-export-2.0"
 fi
 
+# This workaround is required due to a bug in pkg-config file for glib as it
+# doesn't define GLIB_STATIC_COMPILATION for pkg-config --static
+
+if test "$static" = yes && test "$mingw32" = yes; then
+    QEMU_CFLAGS="-DGLIB_STATIC_COMPILATION $QEMU_CFLAGS"
+fi
+
+glib_libs=''
 for i in $glib_modules; do
     if $pkg_config --atleast-version=$glib_req_ver $i; then
-        glib_cflags=$($pkg_config --cflags $i)
-        glib_libs=$($pkg_config --libs $i)
+        if test "$static_glib" != "no" ; then
+            glib_cflags=$($pkg_config --static --cflags $i)
+            glib_libs="$glib_libs $($pkg_config --static --libs $i)"
+        else
+            glib_cflags=$($pkg_config --cflags $i)
+            glib_libs="$glib_libs $($pkg_config --libs $i)"
+        fi
+        QEMU_CFLAGS="$glib_cflags $QEMU_CFLAGS"
     else
         error_exit "glib-$glib_req_ver $i is required to compile QEMU"
     fi
 done
 
-# This workaround is required due to a bug in pkg-config file for glib as it
-# doesn't define GLIB_STATIC_COMPILATION for pkg-config --static
+# This second workaround is required because of the missing libiconv link
+# in case of a static glib.
+if test "$static_glib" != "no" -a "$mingw32" = yes; then
+    LIBS="-Wl,-Bstatic -liconv -Wl,-Bdynamic $LIBS"
+fi
 
-if test "$static" = yes && test "$mingw32" = yes; then
-    glib_cflags="-DGLIB_STATIC_COMPILATION $glib_cflags"
+glib_fixed_lib=''
+# Dirty workaround to only link glib libraries statically and not the
+# system one included by pkg-config.
+if test "$static_glib" != "no" ; then
+    for i in $glib_libs; do
+        if test "$i" != "-lrt" -a "$i" != "-lole32" ; then
+            glib_fixed_lib="$glib_fixed_lib -Wl,-Bstatic $i -Wl,-Bdynamic"
+        else
+            glib_fixed_lib="$glib_fixed_lib $i"
+        fi
+    done
+    LIBS="$glib_fixed_lib $LIBS"
+    libs_qga="$glib_fixed_lib $libs_qga"
+else
+    LIBS="$glib_libs $LIBS"
+    libs_qga="$glib_libs $libs_qga"
 fi
 
 if ! test "$gio" = "no"; then
