configure: introduce --static-glib option
This allows to link with static glib libraries and its dependencies.

TN: T317-002
Change-Id: I4a37483581742d2206f74fc951e8fb71915cabee

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -477,6 +477,7 @@ bogus_os="no"
 malloc_trim=""
 bridge_helper="yes"
 enable_roms="yes"
+static_glib="no"
 
 # parse CC options first
 for opt do
@@ -1428,6 +1429,8 @@ for opt do
   ;;
   --disable-roms) enable_roms="no"
   ;;
+  --static-glib) static_glib="yes"
+  ;;
   *)
       echo "ERROR: unknown option $opt"
       echo "Try '$0 --help' for more information"
@@ -1435,6 +1438,15 @@ for opt do
   ;;
   esac
 done
+
+# Sanity check that we are not trying to enable --static-xxx and -static
+# at the same time.
+if test "$static" = "yes"; then
+    if test "$static_glib" = "yes"; then
+        echo "ERROR: --static and --static-glib are not compatible"
+        exit 1
+    fi
+fi
 
 if test "$vhost_user" = ""; then
     if test "$mingw32" = "yes"; then
@@ -3471,17 +3483,45 @@ if test "$static" = yes -a "$mingw32" = yes; then
     QEMU_CFLAGS="-DGLIB_STATIC_COMPILATION $QEMU_CFLAGS"
 fi
 
+glib_libs=''
 for i in $glib_modules; do
     if $pkg_config --atleast-version=$glib_req_ver $i; then
-        glib_cflags=$($pkg_config --cflags $i)
-        glib_libs=$($pkg_config --libs $i)
+        if test "$static_glib" != "no" ; then
+            glib_cflags=$($pkg_config --static --cflags $i)
+            glib_libs="$glib_libs $($pkg_config --static --libs $i)"
+        else
+            glib_cflags=$($pkg_config --cflags $i)
+            glib_libs="$glib_libs $($pkg_config --libs $i)"
+        fi
         QEMU_CFLAGS="$glib_cflags $QEMU_CFLAGS"
-        LIBS="$glib_libs $LIBS"
-        libs_qga="$glib_libs $libs_qga"
     else
         error_exit "glib-$glib_req_ver $i is required to compile QEMU"
     fi
 done
+
+# This second workaround is required because of the missing libiconv link
+# in case of a static glib.
+if test "$static_glib" != "no" -a "$mingw32" = yes; then
+    LIBS="-Wl,-Bstatic -liconv -Wl,-Bdynamic $LIBS"
+fi
+
+glib_fixed_lib=''
+# Dirty workaround to only link glib libraries statically and not the
+# system one included by pkg-config.
+if test "$static_glib" != "no" ; then
+    for i in $glib_libs; do
+        if test "$i" != "-lrt" -a "$i" != "-lole32" ; then
+            glib_fixed_lib="$glib_fixed_lib -Wl,-Bstatic $i -Wl,-Bdynamic"
+        else
+            glib_fixed_lib="$glib_fixed_lib $i"
+        fi
+    done
+    LIBS="$glib_fixed_lib $LIBS"
+    libs_qga="$glib_fixed_lib $libs_qga"
+else
+    LIBS="$glib_libs $LIBS"
+    libs_qga="$glib_libs $libs_qga"
+fi
 
 # Sanity check that the current size_t matches the
 # size that glib thinks it should be. This catches
